site_name: RKK1995's notes
repo_url: https://github.com/rkk1995/Notes

theme:
  palette:
    # scheme: slate
    primary: indigo
    accent: red
  name: material
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tracking
    # - navigation.top
    # - search.highlight
    # - search.share
    # - search.suggest

  font:
    text: Roboto

plugins:
  - awesome-pages
  - section-index-optional:
      index_file: index.md
    
extra_css:
  - stylesheets/extra.css
  # - stylesheets/headingNumbers.css

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - def_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        toc_depth: 4
    - mdx_truly_sane_lists
    - attr_list
    - pymdownx.tabbed



extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:theravindu@gmail.com
  generator: false
