site_name: RKK1995's notes
repo_url: https://github.com/rkk1995/Notes

theme:
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.top

  font:
    text: Roboto
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'red'
    
extra_css:
  - stylesheets/extra.css
  - stylesheets/headingNumbers.css

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        toc_depth: 0
    - mdx_truly_sane_lists

pages:
    - Home: 'index.md'
    - Papers:
      # - Infrastructure:
      - Storage:
        - aurora: 'aurora/aurora.md'
        - gfs: 'gfs/gfs.md'
        - tao: 'tao/tao.md'
        - craq: 'craq/craq.md'
        - frangipani: 'frangipani/frangipani.md'
        - spanner: 'spanner/spanner.md'
        - farm : 'farm/farm.md'
      - Compute:
        - mapreduce: 'mapreduce/mapreduce.md'
        - distributed transactions : 'distributedTransactions/distributedTransactions.md'
      - Cluster Management:
        - raft : 'raft/raft.md'
        - zookeeper : 'zookeeper/zookeeper.md'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/0xSasuke
    - icon: fontawesome/solid/paper-plane
      link: mailto:theravindu@gmail.com
  generator: false
