site_name: kophy's notes
repo_url: https://github.com/kophy/notes

theme:
  name: 'flatly'

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - mdx_truly_sane_lists

pages:
    - Home: 'index.md'
    - System:
      - Storage:
        - bigtable: 'bigtable/bigtable.md'
        - f1: 'f1/f1.md'
      - Batch:
        - flume: 'flume/flume.md'
      - Streaming:
        - storm: 'storm/storm.md'
      - Cluster:
        - zookeeper: 'zookeeper/zookeeper.md'
      - Low-level:
        - zfs: 'zfs/zfs.md'
    - Machine Learning:
      - Embedding:
        - word2vec: 'word2vec/word2vec.md'
