site_name: kophy's notes
repo_url: https://github.com/kophy/notes

theme:
  name: 'windmill'

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - mdx_truly_sane_lists

pages:
    - Home: 'index.md'
    - Google:
      - bigtable: 'bigtable/bigtable.md'
      - flume: 'flume/flume.md'
    - ML:
      - word2vec: 'word2vec/word2vec.md'
    - Miscellaneous:
      - zfs: 'zfs/zfs.md'
