site_name: RKK1995's notes
repo_url: https://github.com/rkk1995/Notes

theme:
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.top

  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'red'
    

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        toc_depth: 0
    - mdx_truly_sane_lists
    - pymdownx.superfences
    - pymdownx.tabbed

pages:
    - Home: 'index.md'
    - Papers:
      - Infrastructure:
        - Storage:
          - gfs: 'gfs/gfs.md'
          - tao: 'tao/tao.md'
        - Compute:
          - mapreduce: 'mapreduce/mapreduce.md'
        # - Cluster Management:
        #   - borg: 'borg/borg.md'
        #   - zookeeper: 'zookeeper/zookeeper.md'
        # - Misc:
        #   - databus: 'databus/databus.md'
        #   - kafka: 'kafka/kafka.md'
        #   - zfs: 'zfs/zfs.md'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/0xSasuke
    - icon: fontawesome/solid/paper-plane
      link: mailto:theravindu@gmail.com
  generator: false