site_name: RKK1995's notes
repo_url: https://github.com/rkk1995/Notes

theme:
  palette:
    # scheme: slate
    primary: dark blue
    accent: red
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  font:
    text: Roboto

plugins:
  - awesome-pages

    
extra_css:
  - stylesheets/extra.css
  - stylesheets/extra2.css
  - stylesheets/headingNumbers.css

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - def_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        toc_depth: 4
    - mdx_truly_sane_lists
    - attr_list


extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:theravindu@gmail.com
  generator: false
