site_name: RKK1995's notes
repo_url: https://github.com/rkk1995/Notes

theme:
  palette:
    # scheme: slate
    primary: dark blue
    accent: red
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  font:
    text: Roboto


    
extra_css:
  - stylesheets/extra.css
  - stylesheets/extra2.css
  - stylesheets/headingNumbers.css

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - def_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - mdx_math:
        enable_dollar_delimiter: True
    - toc:
        toc_depth: 3
    - mdx_truly_sane_lists
    - attr_list

pages:
    - Home: 'index.md'
    - Papers:
      - Storage:
        - aurora: 'papers/aurora/aurora.md'
        - gfs: 'papers/gfs/gfs.md'
        - tao: 'papers/tao/tao.md'
        - craq: 'papers/craq/craq.md'
        - frangipani: 'papers/frangipani/frangipani.md'
        - spanner: 'papers/spanner/spanner.md'
        - farm : 'papers/farm/farm.md'
        - memcached : 'papers/memcache/memcache.md'
        - dynamo : 'papers/dynamo/dynamo.md'
      - Compute:
        - mapreduce: 'papers/mapreduce/mapreduce.md'
        - distributed transactions : 'papers/distributedTransactions/distributedTransactions.md'
      - Cluster Management:
        - raft : 'papers/raft/raft.md'
        - zookeeper : 'papers/zookeeper/zookeeper.md'
    - Books:
      - Designing Data Intensive Applications:
        - '1. Reliable, Scalable, and Maintainable Applications' : 'books/ddia/chapter1.md'
    - System Design:
      - Concepts:
        - hashtable :
          - basics : 'hashtable/hashtable.md'


extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:theravindu@gmail.com
  generator: false
