site_name: kophy's notes
repo_url: https://github.com/kophy/Notes

theme:
  name: 'sandstone'

extra_javascript:
    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - mdx_truly_sane_lists

pages:
    - Home: 'index.md'
    - Infrastructure:
      - Storage:
        - bigtable: 'bigtable/bigtable.md'
        - f1: 'f1/f1.md'
      - Data Processing:
        - mapreduce: 'mapreduce/mapreduce.md'
        - flume: 'flume/flume.md'
        - rdd: 'rdd/rdd.md'
        - d-stream: 'd-stream/d-stream.md'
        - storm: 'storm/storm.md'
      - Cluster Management:
        - borg: 'borg/borg.md'
        - zookeeper: 'zookeeper/zookeeper.md'
      - Low-level:
        - zfs: 'zfs/zfs.md'
    - Machine Learning:
      - Embedding:
        - word2vec: 'word2vec/word2vec.md'
    - Advertisement:
      - CTR:
        - predicting-clicks: 'predicting-clicks/predicting-clicks.md'
